#!/bin/bash

BASEDIR=$(cd "$(dirname "$0")"; pwd)
cd "$BASEDIR"

if type cargo > /dev/null; then
  cargo build --target wasm32-unknown-unknown --package bigmap --release
else
  echo "Rust `cargo` not installed, not rebuilding wasm"
fi