#!/bin/bash

set -e

BASEDIR=$(cd "$(dirname "$0")"; pwd)
cd "$BASEDIR"

if type cmake >/dev/null; then
  function wasm_optimizer_prepare() {
    # Building ic_cdk_optimizer requires cmake
    cd "$BASEDIR/vendor/rust-cdk/"
    cargo build -p ic_cdk_optimizer
    cd - > /dev/null
  }
  function wasm_optimize() {
    echo "Reducing Wasm size '$1'"
    T=$(mktemp)
    ./vendor/rust-cdk/target/debug/ic_cdk_optimizer -o $T "$1"
    mv $T "$1"
  }
else
  function wasm_optimizer_prepare() {
    echo "Cmake is not installed. Please install it to reduce wasm binary size before uploading."
  };
  function wasm_optimize() { :; }
fi

#
# Search if some files updated and only rebuild if some files in /src changed.
# Otherwise, we'll just keep optimizing the same wasm files in every call.
#

TARGETS=(
target/wasm32-unknown-unknown/release/bigmap_index.wasm
target/wasm32-unknown-unknown/release/bigmap_data.wasm
target/wasm32-unknown-unknown/release/bigmap_search.wasm
)

REBUILD=false
for target in ${TARGETS[@]};
do
  if ! [[ -s "$target" ]] || [[ -n "$(find src/ -newer $target)" ]]; then
    REBUILD=true
  fi
done

if $REBUILD; then
  if type cargo > /dev/null; then
    rustup target add wasm32-unknown-unknown

    cargo build --target wasm32-unknown-unknown --release

    wasm_optimizer_prepare

    for target in ${TARGETS[@]};
    do
      wasm_optimize "$target"
    done
    echo "All targets finished building"
  else
    echo "Rust `cargo` not installed. Please run:"
    echo "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"
  fi
else
  echo "All targets are up to date."
fi

exit 0
