sequenceDiagram
    User Agent            ->> BigMap Index:           Get location of "entry X"
    BigMap Index          ->> User Agent:             "entry X" maps to Data Bucket[i]
    User Agent            ->> BigMap Data Bucket[i]:  Get "entry X"
    BigMap Data Bucket[i] ->> User Agent:             Respond with user's data ("entry X")
