name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build native mode
      run: |
        rustup update
        cargo build
    - name: Release build for wasm32
      run: |
        rustup target add wasm32-unknown-unknown
        cargo build --release --target=wasm32-unknown-unknown
    - name: Run tests
      run: |
        cargo test
    - name: DFX test
      run: |
        echo y | DFX_VERSION=0.6.4 bash -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"
        echo "::add-path::$HOME/bin"
        $HOME/bin/dfx start --background
        $HOME/bin/dfx canister create --all
        bash test.sh
