name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build native mode
      run: cargo build --verbose
    - name: Release build for wasm32
      run: cargo build --release --target=wasm32-unknown-unknown
    - name: Run tests
      run: cargo test --verbose
