name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build native mode
      run: |
        echo y | DFX_VERSION=0.6.4 bash -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        source $HOME/.cargo/env
        rustup target add wasm32-unknown-unknown
        echo "::add-path::$HOME/bin"
        cargo build
    - name: Build wasm32 binaries in release mode
      run: |
        cargo build --release --target=wasm32-unknown-unknown
    - name: Run cargo tests
      run: |
        cargo test
    - name: DFX test
      run: |
        source $HOME/.cargo/env
        echo "dfx cache install"
        dfx cache install
        echo "dfx start --background"
        dfx start --background
        dfx canister create --all
        bash test.sh
